### ISSUE TITLE
Socket errors with --connect option

### ISSUE THREAD

**Issue by PatrikFehrenbach** [mschwager/fierce#11]
Hey guys!

There are several errors when using the --connect page due to the non existence of error handling in the head_request class. 

To avoid connection timeouts i have added a two seconds timeout for each domain, and i have additionally passed every exception occuring (there will be at leas two errors at the current script: 

1. ConnectionRefusedError
2. ConnectionTimedoutError

I have changed the code a bit as a suggestion, for the usability i'd handle the exceptions accordingly and maybe set the timeout as an argument for the user  :-) 

def head_request(url):
    try:
        conn = http.client.HTTPConnection(url,timeout=2)
        conn.request("HEAD", "/")
    except:
         return []
    resp = conn.getresponse()
    conn.close()

best

Patrik

**Comment by mschwager** [comment]
Hey!

Thanks for the feedback! I added some of your suggestions here: https://github.com/mschwager/fierce/commit/1f69dd0a7d30184c838fada4084d09fa0de3ded2

Feel free to add additional suggestions if you have them :)
