### ISSUE TITLE
Doen't work with cloudflare DNS

### ISSUE THREAD

**Issue by technoabh** [mschwager/fierce#14]
netwrkspider@linuxzone:~/fierce$ ./fierce.py --domain 00studios.com --subdomains accounts admin ads
NS: rose.ns.cloudflare.com. nick.ns.cloudflare.com.
SOA: nick.ns.cloudflare.com. (173.245.59.213)
Zone: failure
Wildcard: failure

**Comment by mschwager** [comment]
I can query that domain:

```
$ dig 00studios.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> 00studios.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51545
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;00studios.com.			IN	A

;; ANSWER SECTION:
00studios.com.		299	IN	A	104.31.93.211
00studios.com.		299	IN	A	104.31.92.211

;; Query time: 41 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Wed Aug 03 14:00:25 EDT 2016
;; MSG SIZE  rcvd: 74
```

But, from what I can tell, those subdomains don't exist:

```
$ dig admin.00studios.com @8.8.8.8

; <<>> DiG 9.10.3-P4-Ubuntu <<>> admin.00studios.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18341
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;admin.00studios.com.		IN	A

;; AUTHORITY SECTION:
00studios.com.		1779	IN	SOA	nick.ns.cloudflare.com. dns.cloudflare.com. 2019730597 10000 2400 604800 3600

;; Query time: 27 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Aug 03 14:02:11 EDT 2016
;; MSG SIZE  rcvd: 107
```

I don't believe this is an issue with `Cloudflare` or `fierce`.

Thoughts?

**Comment by mschwager** [comment]
Feel free to re-open if you continue to have issues!

**Comment by l4jos** [comment]
Those IP's are two CloudFlare addresses, but there is a way to find origin IP. Ping or DIG will not give you the information you want if you see CloudFlare in stdout (2 IP's sometimes indicates a firewall)

I recommend to look for DNS zone transfer history. If the server outside LAN is set-up once correctly, and when it goes behind a firewall (e.g. cloudflare) some websites keep a record of this nameserver change including the very first IP. That is still often the real IP.
