### ISSUE TITLE
Problem for two subdomains separated by dot with --subdomain-file

### ISSUE THREAD

**Issue by johanmazel** [mschwager/fierce#17]
When I use --subdomain-file with subdomains each composed of two subdomains separated by a dot (e.g. "toto.tata"), I do not get an answer.
By putting some print inside fierce, I found that the problem comes from this line : "result = dns.name.Name(tuple(subdomains) + domain.labels)".
It replaces dots in subdomains by "\.".
For example, the subdomain "toto.tata" becomes "toto\.tata" which causes the DNS request to fail.

Is this an expected behavior ?
Am I not supposed to use the --subdomain-file option with this kind of input?

**Comment by mschwager** [comment]
I think this may be related to https://github.com/mschwager/fierce/pull/12. I'll take a look. Thanks for the heads up!

**Comment by johanmazel** [comment]
Sorry, I made a formatting mistake.
I meant:
It replaces dots (".") in subdomains by "\\.".
For example, the subdomain "toto.tata" becomes "toto\\.tata" which causes the DNS request to fail.

**Comment by mschwager** [comment]
Hey @johanmazel! I believe https://github.com/mschwager/fierce/commit/27bed0c971a04fd737b8804469cf2f34938043cd should fix your issue :)
