### ISSUE TITLE
`dns.name.EmptyLabel` stack trace

### ISSUE THREAD

**Issue by timmc** [mschwager/fierce#20]
I received this using fierce 1.1.5 (installed via python3-pip) when doing a basic scan of my domain, `brainonfire.net`, with the 20k subdomain list:

```
Traceback (most recent call last):
  File "/usr/local/bin/fierce", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/fierce.py", line 405, in main
    fierce(**vars(args))
  File "/usr/local/lib/python3.4/dist-packages/fierce.py", line 284, in fierce
    url = concatenate_subdomains(domain, [subdomain])
  File "/usr/local/lib/python3.4/dist-packages/fierce.py", line 86, in concatenate_subdomains
    result = dns.name.Name(tuple(subdomains) + domain.labels)
  File "/usr/local/lib/python3.4/dist-packages/dns/name.py", line 329, in __init__
    _validate_labels(self.labels)
  File "/usr/local/lib/python3.4/dist-packages/dns/name.py", line 299, in _validate_labels
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.
```

**Comment by timmc** [comment]
OK, this is because there are some fully qualified domain names in the `lists/20000.txt` file, such as `ns3.cl.bellsouth.net.`. That trailing dot leads to an empty name segment.

While there should be error-handling around empty name segments, I'd also be happy to submit a PR pruning out some junk from the sample subdomain list files:

- Remove FQDNs
- Lowercasing all names
- Removing duplicates caused by case-folding (there are only 13 of those, I think)

Let me know if that would be welcome.

**Comment by timmc** [comment]
Ended up needing to do it anyway, so here's a PR that at least cleans the sample lists: https://github.com/mschwager/fierce/pull/21

**Comment by mschwager** [comment]
Hey @timmc! Thanks for noticing this! I think I would prefer to fix the issue in code instead of in the subdomain lists. That way if we ever encounter subdomains specified in this way they will be properly cleaned. I commit a fix :)

**Comment by timmc** [comment]
Great, thanks! Should I close the list-cleaning PR then? (Or you can, of course.)
