### ISSUE TITLE
Timeout from DNS resolver crashes program

### ISSUE THREAD

**Issue by timmc** [mschwager/fierce#22]
If the DNS resolver gets a timeout, the program crashes:

```
  File "./fierce.py", line 408, in <module>
    main()
  File "./fierce.py", line 405, in main
    fierce(**vars(args))
  File "./fierce.py", line 285, in fierce
    record = query(resolver, url, record_type='A')
  File "./fierce.py", line 96, in query
    resp = resolver.query(domain, record_type, raise_on_no_answer=False)
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.00057625770569 seconds
```

I don't see a way to prevent that, but perhaps exceptions raised for any one subdomain should be reported and suppressed so the program can continue to run.

**Comment by mschwager** [comment]
Thanks again for reporting! Yes! We should definitely continue searching even if one query times out. I'll commit a fix!

**Comment by timmc** [comment]
Looks good!

Might be worth moving the whole subdomain loop body to a function and wrapping it in a more general exception handler -- I think besides the EmptyLabel and Timeout exceptions, I might have seen another one. I'll report it if I see it, but a more general solution (skip ones in error? die, but allow restarting from next subdomain position?) might be worth considering.

**Comment by mschwager** [comment]
Yeah, I need to find a way to handle exceptions better. It feels like I'm playing whack-a-mole with all the possible network/DNS errors. Perhaps the best way forward would be catching exceptions generally, logging them, and moving on. Although, some exceptions may be more dire than others. Hmm, probably requires some further investigation...
