### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by tholu** [mschwager/fierce#24]
A [Homebrew](https://github.com/Homebrew/homebrew-core) formula would be nice for easy install under MacOS.

**Comment by simontoft** [comment]
Is this really necessary?

You can just do:
sudo python -m ensurepip
sudo pip install fierce

or:
brew install brew-pip
brew pip fierce

**Comment by tholu** [comment]
Did not now about `brew-pip`, but does not work for me, e.g.
```
➜  ~ brew pip fierce
/usr/local/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting fierce
  Could not find a version that satisfies the requirement fierce (from versions: )
No matching distribution found for fierce
Error: No such keg: /usr/local/Cellar/pip-fierce
```
What am I doing wrong?

**Comment by tholu** [comment]
`sudo -H pip3 install fierce` worked though, easy enough I guess.
