### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by StringManolo** [mschwager/fierce#44]
Got this error:
```bash
$ fierce --domain example.com
NS: a.iana-servers.net. b.iana-servers.net.
SOA: ns.icann.org. (199.4.138.53)
Zone: failure
Traceback (most recent call last):
  File "/usr/bin/fierce", line 33, in <module>
    sys.exit(load_entry_point('fierce==1.5.0', 'console_scripts', 'fierce')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fierce-1.5.0-py3.12.egg/fierce/fierce.py", line 495, in main
    fierce(**vars(args))
  File "/usr/lib/python3.12/site-packages/fierce-1.5.0-py3.12.egg/fierce/fierce.py", line 338, in fierce
    random_subdomain = str(random.randint(1e10, 1e11))  # noqa DUO102, non-cryptographic random use
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```

Fixed it by replacing:
```python
random_subdomain = str(random.randint(1e10, 1e11)) 
```

by

```
random_subdomain = str(random.randint(10000000000, 99999999999))
```

The line is:
https://github.com/mschwager/fierce/blob/f32f639817e642ab3e4ba680941de3e64b8b681c/fierce/fierce.py#L338

**Comment by StringManolo** [comment]
> Ahh, interesting, I see `random.randint`'s behavior [changed in Python 3.12](https://docs.python.org/3/library/random.html#random.randrange). Initially I thought that the scientific notation syntax changed it's type from `int` to `float`, but it appears that it's always been a `float`.
> 
> How do you feel about the following change instead?
> 
> ```python
> random_subdomain = str(random.randint(int(1e10), int(1e11)))
> ```
> 
> It feels like it retains the original behavior slightly better to me. Would you be interested in opening a PR to fix it?

Ye, that solution is much better.

**Comment by mschwager** [comment]
> hello, still having this issue but it works with the suggested fix `random_subdomain = str(random.randint(int(1e10), int(1e11)))`

Thanks for the confirmation, I'll fix this tomorrow and release a new version.

**Comment by mschwager** [comment]
Version 1.6.0 has been released with the fix: https://pypi.org/project/fierce/1.6.0/
